trigger:
- dev


jobs:
- job: MainWindows
  timeoutInMinutes: 0
  strategy:
    matrix:
      release:
        config: 'Release'
      debug:
        config: 'Debug'


  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: '-DCMAKE_BUILD_TYPE=$(config) -G -DLIBIGL_WITH_CGAL=ON -DLIBIGL_WITH_COMISO=OFF "Visual Studio 15 2017 Win64" ..'

  - task: VSBuild@1
    inputs:
      solution: 'build/libigl.sln'
      vsVersion: '15.0'
      platform: 'x64'
      configuration: $(config)
      maximumCpuCount: true
      msbuildArchitecture: 'x64'
