trigger:
- dev


jobs:
- job: MainWindows
  timeoutInMinutes: 0
  strategy:
    matrix:
      release:
        config: 'Release'
      debug:
        config: 'Debug'


  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: '-DCMAKE_BUILD_TYPE=$(config) -G "Visual Studio 15 2017 Win64" -DLIBIGL_WITH_CGAL=ON -DLIBIGL_WITH_COMISO=OFF ..'

  - task: VSBuild@1
    inputs:
      solution: 'build/libigl.sln'
      vsVersion: '15.0'
      platform: 'x64'
      configuration: $(config)
      maximumCpuCount: true
      msbuildArchitecture: 'x64'
  
  - task: CmdLine@2
    inputs:
      script: |
        set CTEST_OUTPUT_ON_FAILURE=1
        cd build
        ctest  -C $(config) -V --output-on-failure -j --no-compress-output -O TEST-igl.xml
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'CTest'
      testResultsFiles: '**/TEST-*.xml'


- job: MainMacos
  timeoutInMinutes: 0
  strategy:
    matrix:
      release:
        config: 'Release'
      debug:
        config: 'Debug'


  pool:
    vmImage: 'macos-10.13'

  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: '-DCMAKE_BUILD_TYPE=$(config) -DLIBIGL_WITH_CGAL=ON -DLIBIGL_CHECK_UNDEFINED=ON ..'

  - task: CmdLine@2
    inputs:
      script: |
        cd build
        make -j
  
  - task: CmdLine@2
    inputs:
      script: |
        cd build
        ctest -V --output-on-failure -j --no-compress-output -O TEST-igl.xml
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'CTest'
      testResultsFiles: '**/TEST-*.xml'
